name: lit_example
description: lit-html example
version: 0.0.1
homepage: https://github.com/xxgreg
author: Greg <greg@v7.nz>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.0
  source_gen: ^0.7.2+1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  #source_gen: ^0.7.2+1
  build_runner: ^0.6.0+1

transformers:
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
